### ISSUE TITLE
AttributeError: 'ElementTree' object has no attribute 'xpath'

### ISSUE THREAD

**Issue by Analect** [bryantbhowell/tableau_rest_api#1]
@bryantbhowell 
Thanks for your work on this.
I've been experimenting with your repo and have hit some snags - perhaps you can point me in the right direction.
I've been partly referencing your blog post: https://tableauandbehold.wordpress.com/2015/05/26/getting-started-with-the-tableau_rest_api-library/

I'm using ver 2.7.6 of python in a virtualenv with the following packages installed (the repo would benefit from requirements.txt file). I think these are the only non-core packages required.
argparse==1.2.1
lxml==3.4.4
wsgiref==0.1.2

Your blog suggests Tableau Server is installed locally (ip= '127.0.0.1').  Is it a requirement that this repo be installed on the same machine as the server?

When I try using the ip address for my server hosted on AWS 
```tab_srv = tableau_rest_api.TableauRestApi('xxx.xxx.xxx.xxx', 'my_username', 'my_password', site_content_url='a_site_within_the_server')```, I get:
```
ValueError: unknown url type: xxx.xxx.xxx.xxx/api/2.0/auth/signin
```

It works if I add http://: 
```tab_srv = tableau_rest_api.TableauRestApi('http://xxx.xxx.xxx.xxx', 'my_username', 'my_password', site_content_url='a_site_within_the_server')```

However, when attempting to sign-in, I then get:
```
>> tab_srv.signin()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/mccoole/PycharmProjects/tableau_rest_api/tableau_rest_api.py", line 238, in signin
    api.request_from_api(0)
  File "/home/mccoole/PycharmProjects/tableau_rest_api/tableau_rest_api.py", line 1517, in request_from_api
    for pagination in xml.xpath('//t:pagination', namespaces=self.__ns_map):
AttributeError: 'ElementTree' object has no attribute 'xpath'
```
Thanks for your input.

**Comment by bryantbhowell** [comment]
Hi Analect,
Thank you for writing to me. I'm actually fairly new at Python, particularly packaging things up, so I really appreciate the suggestions. I've just uploaded a new version of the package including a requirements.txt. It's also built with setuptools so it should enforce the requirement for lxml on install, although I'm still working to make sure that all works as expected. Do you know where argparse and wsgiref are being used -- I'm not aware of using them but if they are required for something, I'm happy to add them as requirements.

You are correct that the server location needs either 'http://' or 'https://'. You should always specify 'https://' if the server is secured with SSL, otherwise there are strange redirects that go on. An exception now throws if 'http' isn't found in the URL with a message explaining why. I also updated that blog post -- I just realized I had it up incorrectly. It will work with any server you have access to, not just localhost.

For the exception you are seeing, it'll be easier to know what is happening by looking at the logs created on the logger object. They show the actual XML and URIs.

**Comment by Analect** [comment]
@bryantbhowell 
Thanks for coming back on this.
Did you push your changes to Github ... I don't see the requirements / setup you refer to.

I think the argparse / wsgiref packages must be dependencies of some lxml tests.
http://lxml.de/api/lxml.tests.dummy_http_server.WebServer-class.html

I had set up a virtualenv for this project folder ... and used pip freeze to see what packages had been installed.  I'm using pycharm ... which is then pointing at that virtualenv as its python interpreter.

![image](https://cloud.githubusercontent.com/assets/4063815/7963778/590a7098-0a0c-11e5-8848-416ac1216b2a.png)

I'm not altogether sure why pycharm is not happy to import the tableau_rest_api module ... (you can see it grayed-out below) ... anyway, I ended up importing the various items and setting the initial variables in your test file by hand ... it seems I have to change references to 'rest_api' to 'tableau_rest_api' to get this to work.

The red square below was my attempt to get this working yesterday (ver. 1.04, I think) ... you can see it coming back with some pagination error.

The green square is my attempt to 'sign_in' today based on v. 1.05 ... with a slightly different error response.

It appears that although rest_test.log is getting created, there isn't anything being logged to the file.

![tableau_rest_api1](https://cloud.githubusercontent.com/assets/4063815/7963730/188b5f1e-0a0c-11e5-889e-a0c0e45d396c.png)

I believe my server is enabled by default for REST API interaction ... in order to isolate the problem, is there any demo server running that I could try connecting to ... and see if that works?

Thanks,
Colum

**Comment by Analect** [comment]
@bryantbhowell 
Thanks for updating the repo.
I have been able to get most of the test file to run, with a few modifications but at some point it errored out ... perhaps you can help to isolate the problem.

I had to change all the 'rest_api' references in the test file to 'tableau_rest_api'.
The flights tde/twbx files you use are obviously not in the repo ... but I found something equivalent here: http://public.tableau.com/views/OpenFlightsDataExplorer/FlightExplorer?:embed=y&:display_count=no&:showVizHome=no

...using 'Lines Out.tde' and 'OpenFlights Data Explorer.twbx', as per screenshot below.

![tableau_rest_api3](https://cloud.githubusercontent.com/assets/4063815/7985139/72c3ef2c-0ac6-11e5-8676-b9c1feb4aee0.png)

The code was running fine until around line 158 of the test file.
Then it was somehow getting muddled ... thinking that there was a user 'False' that couldn't be found ... I was just wondering if one of the function calls might have fed 'False' as a wrong parameter?  Line 158 calls: tab_srv_3.update_workbook_by_luid(new_wb_luid, sandbox_luid, False, True)

![tableau_rest_api2](https://cloud.githubusercontent.com/assets/4063815/7985133/60af813e-0ac6-11e5-80cd-8a229be8c859.png)

The only other errors (beyond this 404002 one above) in the log file ... was a series of 404014 errors ... arising from the section around line 102 of the test file to do with sandbox permissioning.  I'm obviously using my own credentials to login ... and as Server Administrator .. I didn't expect a limitation on being able to set permissions etc...  not sure if you have any idea what might be going wrong here and if it is related in any way to the 404002 error later on.

![tableau_rest_api4](https://cloud.githubusercontent.com/assets/4063815/7985464/dae7c2b6-0ac8-11e5-9244-c067e46c6e22.png)

One final thing:
Is there a way that this tool can be used to programmatically structure a shell twbx file referencing a pre-published data source ... where the fields and any joins etc..(assume this meta-data is stored external from Tableau to begin with) are pre-seeded, so a a user viewing the workbook online can already see some available data with which to build a basic visualisation.

![tableau_rest_api5](https://cloud.githubusercontent.com/assets/4063815/7985713/9e828fc0-0aca-11e5-8b5c-269bcf085490.png)

Thanks again,
Colum

**Comment by Analect** [comment]
@bryantbhowell 
Just wondering if you had any time to look at my comment above from a few weeks back. Thanks.

**Comment by bryantbhowell** [comment]
Hi Analect,
I've updated the library quite a bit in the way of permissions (https://tableauandbehold.wordpress.com/2015/06/18/setting-permissions-in-the-tableau-with-the-rest-api/ has the full explanation) and also put up an updated version of the test script, which runs through all the way on my system. There is nothing special to any of the files that I am publishing, they are just there as examples of all the different types that can be posted up.

We normally just think of publishing the datasources rather than a shell TWBX that includes them, because you can trigger a new workbook based on that datasource using the following URL pattern: 
http://localhost/authoringNewWorkbook/{datasourceURI} (ex. http://localhost/authoringNewWorkbook/AccountSalesforce ).

You can definitely edit the XML in a TWB to point to different datasources, then publish each variation as its own workbook. The REST API library can be used for the publishing portion, you'll have to work out what details needs to be changed in the TWB, but it's fairly obvious once you open the files up. 

Let me know if there is anything else not working or incorrectly documented now.

**Comment by Analect** [comment]
Great. Thanks.
